"""OS-aware service installer for the superharness watcher.

Selects the correct background-service backend at runtime:

  - macOS  → launchd (plist generated by install-launchd-inbox-watcher.sh)
  - Linux  → systemd (install-systemd-inbox-watcher.sh)
  - Windows → Windows Task Scheduler (schtasks.exe, native inbox loop)
  - Other  → foreground mode only (prints instructions)

Public API
----------
detect_backend() -> str
    Return the backend name for the current OS.

install(project_dir, worker_dir, scripts_dir, opts) -> bool
    Install the watcher service using the detected backend.
    Returns True on success, False on failure.

uninstall(project_dir, scripts_dir) -> bool
    Remove the watcher service (best-effort; returns False if already absent).
"""
from __future__ import annotations

import os
import platform
import subprocess
import sys
from pathlib import Path


def _resolve_script(scripts_dir: Path, script_name: str) -> Path:
    """Resolve a watcher installer script from current or legacy layouts."""
    candidate = scripts_dir / script_name
    if candidate.is_file():
        return candidate

    package_scripts_dir = Path(__file__).resolve().parent.parent / "scripts"
    candidate = package_scripts_dir / script_name
    if candidate.is_file():
        return candidate

    repo_scripts_dir = Path(__file__).resolve().parent.parent.parent.parent / "scripts"
    return repo_scripts_dir / script_name


# ---------------------------------------------------------------------------
# Backend detection
# ---------------------------------------------------------------------------


def detect_backend() -> str:
    """Return the service backend name for the current OS.

    Returns:
        One of ``'launchd'``, ``'systemd'``, ``'winsvc'``, ``'foreground'``.
    """
    system = platform.system()
    if system == "Darwin":
        return "launchd"
    if system == "Linux":
        return "systemd"
    if system == "Windows":
        return "winsvc"
    return "foreground"


# ---------------------------------------------------------------------------
# macOS launchd
# ---------------------------------------------------------------------------


def _install_launchd(
    project_dir: Path,
    worker_dir: Path,
    scripts_dir: Path,
    *,
    interval: int,
    recover_timeout: int,
    recover_action: str,
    launcher_timeout: int,
    to: str,
    codex_bypass: bool,
) -> bool:
    script = _resolve_script(scripts_dir, "install-launchd-inbox-watcher.sh")
    if not script.is_file():
        print(f"Warning: launchd install script not found: {script}", file=sys.stderr)
        return False

    args = [
        "bash", str(script),
        "--project", str(worker_dir),
        "--interval", str(interval),
        "--recover-timeout-minutes", str(recover_timeout),
        "--recover-action", recover_action,
        "--launcher-timeout", str(launcher_timeout),
        "--to", to,
        "--confirm-non-interactive", "yes",
        "--confirm-skip-permissions", "yes",
    ]
    if codex_bypass:
        args += ["--codex-bypass", "--confirm-codex-bypass", "yes"]

    result = subprocess.run(args, check=False)
    return result.returncode == 0


def _uninstall_launchd(project_dir: Path, scripts_dir: Path) -> bool:
    script = _resolve_script(scripts_dir, "uninstall-launchd-inbox-watcher.sh")
    if not script.is_file():
        return False
    result = subprocess.run(["bash", str(script), "--project", str(project_dir)], check=False)
    return result.returncode == 0


# ---------------------------------------------------------------------------
# Linux systemd
# ---------------------------------------------------------------------------


def _install_systemd(
    project_dir: Path,
    worker_dir: Path,
    scripts_dir: Path,
    **_kwargs: object,
) -> bool:
    script = _resolve_script(scripts_dir, "install-systemd-inbox-watcher.sh")
    if not script.is_file():
        print(
            "INFO: systemd install script not found. "
            "Run 'superharness watch --foreground --project .' to start the watcher manually.",
            file=sys.stderr,
        )
        return False
    result = subprocess.run(
        ["bash", str(script), "--project", str(worker_dir)], check=False
    )
    return result.returncode == 0


def _uninstall_systemd(project_dir: Path, scripts_dir: Path) -> bool:
    script = _resolve_script(scripts_dir, "uninstall-systemd-inbox-watcher.sh")
    if not script.is_file():
        return False
    result = subprocess.run(["bash", str(script), "--project", str(project_dir)], check=False)
    return result.returncode == 0


# ---------------------------------------------------------------------------
# Windows Task Scheduler
# ---------------------------------------------------------------------------

_TASK_NAME_PREFIX = "SuperharnessWatcher"


def _schtasks_task_name(worker_dir: Path) -> str:
    """Derive a unique Task Scheduler task name from the worker path."""
    import hashlib
    key = hashlib.sha1(str(worker_dir).encode()).hexdigest()[:8]
    safe = worker_dir.name.replace(" ", "_")[:24]
    return f"{_TASK_NAME_PREFIX}_{safe}_{key}"


def _install_winsvc(
    project_dir: Path,
    worker_dir: Path,
    scripts_dir: Path,
    *,
    interval: int,
    recover_timeout: int,
    recover_action: str,
    launcher_timeout: int,
    to: str,
    codex_bypass: bool,
    **_kwargs: object,
) -> bool:
    """Register a Windows Task Scheduler task that runs the watcher on a repeating interval.

    Uses ``schtasks.exe`` (ships with every Windows edition since XP) to
    create a task that launches:

        python -m superharness.commands.inbox_watch
            --project <worker_dir>
            --once
            --to <to>
            [--codex-bypass]
            --recover-timeout-minutes <n>
            --recover-action <action>
            --launcher-timeout <n>

    The task runs as the current user on login and then every <interval> minutes
    (minimum 1 minute per Task Scheduler constraints — sub-minute intervals are
    achieved by the ``--once`` single-cycle model called by a 1-minute trigger
    with a repetition interval).
    """
    task_name = _schtasks_task_name(worker_dir)
    python_exe = sys.executable

    watch_cmd_parts = [
        python_exe, "-m", "superharness.commands.inbox_watch",
        "--project", str(worker_dir),
        "--once",
        "--to", to,
        "--recover-timeout-minutes", str(recover_timeout),
        "--recover-action", recover_action,
        "--launcher-timeout", str(launcher_timeout),
    ]
    if codex_bypass:
        watch_cmd_parts.append("--codex-bypass")

    # Task Scheduler requires the program and arguments to be separate
    program = watch_cmd_parts[0]
    arguments = " ".join(f'"{a}"' if " " in a else a for a in watch_cmd_parts[1:])

    # Interval in minutes (minimum 1)
    interval_min = max(1, interval // 60) if interval >= 60 else 1
    repeat_interval = f"PT{interval_min}M"

    # Use schtasks /Create to register a ONCE trigger with repetition
    # /F = force (overwrite if exists), /RL HIGHEST = run with highest privileges available
    schtasks_args = [
        "schtasks", "/Create", "/F",
        "/TN", task_name,
        "/TR", f'"{program}" {arguments}',
        "/SC", "MINUTE",
        "/MO", str(interval_min),
        "/RL", "HIGHEST",
    ]

    result = subprocess.run(schtasks_args, check=False, capture_output=True, text=True)
    if result.returncode != 0:
        print(
            f"Warning: Task Scheduler registration failed (rc={result.returncode}).\n"
            f"  stderr: {result.stderr.strip()}\n"
            "  You can run the watcher manually with:\n"
            f"  superharness watch --foreground --project .",
            file=sys.stderr,
        )
        return False

    print(f"Windows Task Scheduler task registered: {task_name}")
    print(f"  Runs every {interval_min} minute(s) for project: {worker_dir}")
    return True


def _uninstall_winsvc(project_dir: Path, **_kwargs: object) -> bool:
    """Delete all Task Scheduler tasks for the given project."""
    import hashlib

    # Best-effort: enumerate tasks with our prefix and delete any that match
    list_result = subprocess.run(
        ["schtasks", "/Query", "/FO", "CSV", "/NH"],
        capture_output=True, text=True, check=False,
    )
    if list_result.returncode != 0:
        return False

    deleted = 0
    for line in list_result.stdout.splitlines():
        # CSV format: "TaskName","Next Run Time","Status"
        parts = line.strip('"').split('","')
        if not parts:
            continue
        name = parts[0].lstrip("\\")
        if name.startswith(_TASK_NAME_PREFIX):
            del_result = subprocess.run(
                ["schtasks", "/Delete", "/TN", name, "/F"],
                capture_output=True, text=True, check=False,
            )
            if del_result.returncode == 0:
                deleted += 1

    return deleted > 0


# ---------------------------------------------------------------------------
# Public install / uninstall interface
# ---------------------------------------------------------------------------


def install(
    project_dir: Path,
    worker_dir: Path,
    scripts_dir: Path,
    *,
    interval: int = 15,
    recover_timeout: int = 3,
    recover_action: str = "retry",
    launcher_timeout: int = 180,
    to: str = "both",
    codex_bypass: bool = False,
) -> bool:
    """Install the watcher service using the OS-appropriate backend.

    Args:
        project_dir:      Source project directory (used to derive config).
        worker_dir:       Worker copy directory (what the watcher process uses).
        scripts_dir:      Path to the superharness scripts/ directory.
        interval:         Poll interval in seconds.
        recover_timeout:  Stale-item recovery timeout in minutes.
        recover_action:   ``'stale'`` or ``'retry'``.
        launcher_timeout: Max seconds to wait for agent launch.
        to:               Agent target: ``'both'``, ``'claude-code'``, or ``'codex-cli'``.
        codex_bypass:     If True, pass ``--codex-bypass`` to the watcher.

    Returns:
        ``True`` if the service was installed successfully, ``False`` otherwise.
    """
    backend = detect_backend()
    kwargs = dict(
        project_dir=project_dir,
        worker_dir=worker_dir,
        scripts_dir=scripts_dir,
        interval=interval,
        recover_timeout=recover_timeout,
        recover_action=recover_action,
        launcher_timeout=launcher_timeout,
        to=to,
        codex_bypass=codex_bypass,
    )

    if backend == "launchd":
        return _install_launchd(**kwargs)
    if backend == "systemd":
        return _install_systemd(**kwargs)
    if backend == "winsvc":
        return _install_winsvc(**kwargs)

    # foreground — print guidance only
    print(
        f"INFO: Automatic service install is not supported on {platform.system()}.\n"
        "      Start the watcher manually with:\n"
        "        superharness watch --foreground --project ."
    )
    return False


def uninstall(project_dir: Path, scripts_dir: Path) -> bool:
    """Uninstall the watcher service for *project_dir*.

    Args:
        project_dir: Source project directory.
        scripts_dir: Path to the superharness scripts/ directory.

    Returns:
        ``True`` if something was removed, ``False`` if nothing found or error.
    """
    backend = detect_backend()
    if backend == "launchd":
        return _uninstall_launchd(project_dir, scripts_dir)
    if backend == "systemd":
        return _uninstall_systemd(project_dir, scripts_dir)
    if backend == "winsvc":
        return _uninstall_winsvc(project_dir)
    return False
